// Generated by scripts/generate-release-content.mjs. Edit release-content/release-intro.md, CHANGELOG.md, or src/config.js instead.
export const BUNDLED_RELEASE_NOTES = {
    "schemaVersion": 1,
    "releaseVersion": "2.8.1",
    "developerNotice": {
        "title": "開發者想說的話",
        "paragraphs": [
            {
                "segments": [
                    {
                        "text": "抱歉這次卡了很久才更新Q_Q，中間我跑去做"
                    },
                    {
                        "label": "為你的世界買單",
                        "url": "https://shopyourvalues.app/"
                    },
                    {
                        "text": "平台\n不小心一時忘了要去修留友封的bug我很抱歉..."
                    }
                ]
            },
            {
                "segments": [
                    {
                        "text": "BTW，"
                    },
                    {
                        "label": "為你的世界買單",
                        "url": "https://shopyourvalues.app/"
                    },
                    {
                        "text": "是一個能輸入品牌名稱，查詢公開資訊的平台。讓你在買商品之前，了解企業所為。\n有興趣的也可以玩看看"
                    }
                ]
            },
            {
                "segments": [
                    {
                        "text": "這次留友封修正了幾個使用者回應的問題"
                    }
                ]
            },
            {
                "segments": [
                    {
                        "text": "1:碰到有興趣標籤封鎖流程會停下來的問題"
                    }
                ]
            },
            {
                "segments": [
                    {
                        "text": "2:在訊息頁面中留友封menu亂置"
                    }
                ]
            },
            {
                "segments": [
                    {
                        "text": "3:清理名單的混亂機制"
                    }
                ]
            },
            {
                "segments": [
                    {
                        "text": "4:三無掃描的穩定性"
                    }
                ]
            },
            {
                "segments": [
                    {
                        "text": "5:部份使用者有回報2.8.0封鎖會失敗，這次2.8.1有試著修正這一塊\n如果有問題還請回報"
                    }
                ]
            },
            {
                "segments": [
                    {
                        "text": "並同時修改了介面讓設定看起來更乾淨"
                    }
                ]
            },
            {
                "segments": [
                    {
                        "text": "另外，有網友回報說留友封跟哩素隨在Firefox上會有衝突\n如果你有碰到這個問題，歡迎回報，我需要更多的資訊才比較好做修正\n感謝大家!"
                    }
                ]
            }
        ]
    },
    "updateSection": {
        "title": "最近更新",
        "items": [
            {
                "version": "2.8.1",
                "text": "修正封鎖執行期間帳號列勾選框反覆亮起又消失的問題。原因是勾選狀態在程式裡有六份各自為政的判斷，來源不一致、更新週期也不同，互相覆蓋才造成閃爍；本次收斂為單一判斷來源。"
            },
            {
                "version": "2.8.0",
                "text": "移除 Chrome「加速三無」的 credentials／token 處理路徑，留友封不再要求或處理 Threads 密碼、雙因素驗證碼、request token 或 session cookie；平台同步同意升為 platform-sync-v4，新增「公開文字片段可能由人工讀取」的誠實揭露，既有使用者需重新同意；設定介面改為三分頁，示範觀測平台已移除。"
            },
            {
                "version": "2.7.4",
                "text": "主要修正有興趣標籤造成封鎖流程中斷、訊息頁面板位置錯亂、清理名單收集不穩與三無掃描無法順利停止或重新啟動等問題，並重新整理設定介面。"
            },
            {
                "version": "2.7.3",
                "text": "補上 Firefox AMO 一鍵送件流程，並修正本次正式版發版產物來源，避免把 stale beta artifact 上傳到商店。"
            }
        ]
    },
    "supportMessage": "如果留友封有幫上你的忙，也歡迎贊助我來維持功能更新；或到 Chrome Web Store 留一句評價，讓更多人敢安心安裝。謝謝大家的支持。"
};
