// Generated by scripts/generate-release-content.mjs. Edit release-content/release-intro.md, CHANGELOG.md, or src/config.js instead.
export const BUNDLED_RELEASE_NOTES = {
    "schemaVersion": 1,
    "releaseVersion": "2.7.4",
    "developerNotice": {
        "title": "開發者想說的話",
        "paragraphs": [
            {
                "segments": [
                    {
                        "text": "抱歉這次卡了很久才更新Q_Q，中間我跑去做"
                    },
                    {
                        "label": "為你的世界買單",
                        "url": "https://shopyourvalues.app/"
                    },
                    {
                        "text": "平台\n不小心一時忘了要去修留友封的bug我很抱歉..."
                    }
                ]
            },
            {
                "segments": [
                    {
                        "text": "BTW，"
                    },
                    {
                        "label": "為你的世界買單",
                        "url": "https://shopyourvalues.app/"
                    },
                    {
                        "text": "是一個能輸入品牌名稱，查詢公開資訊的平台。讓你在買商品之前，了解企業所為。\n有興趣的也可以玩看看"
                    }
                ]
            },
            {
                "segments": [
                    {
                        "text": "這次留友封修正了幾個使用者回應的問題"
                    }
                ]
            },
            {
                "segments": [
                    {
                        "text": "1:碰到有興趣標籤封鎖流程會停下來的問題"
                    }
                ]
            },
            {
                "segments": [
                    {
                        "text": "2:在訊息頁面中留友封menu亂置"
                    }
                ]
            },
            {
                "segments": [
                    {
                        "text": "3:清理名單的混亂機制"
                    }
                ]
            },
            {
                "segments": [
                    {
                        "text": "4:三無掃描的穩定性"
                    }
                ]
            },
            {
                "segments": [
                    {
                        "text": "並同時修改了介面讓設定看起來更乾淨"
                    }
                ]
            },
            {
                "segments": [
                    {
                        "text": "另外，有網友回報說留友封跟哩素隨在Firefox上會有衝突\n如果你有碰到這個問題，歡迎回報，我需要更多的資訊才比較好做修正\n感謝大家!"
                    }
                ]
            }
        ]
    },
    "updateSection": {
        "title": "最近更新",
        "items": [
            {
                "version": "2.7.4",
                "text": "主要修正有興趣標籤造成封鎖流程中斷、訊息頁面板位置錯亂、清理名單收集不穩與三無掃描無法順利停止或重新啟動等問題，並重新整理設定介面。"
            },
            {
                "version": "2.7.3",
                "text": "補上 Firefox AMO 一鍵送件流程，並修正本次正式版發版產物來源，避免把 stale beta artifact 上傳到商店。"
            },
            {
                "version": "2.7.2",
                "text": "新增跨設備加密回報包匯出 / 匯入，修正三無待審清單與回文彈窗清理入口，並更新正式版內建說明、CWS 留評入口與官網信任資訊。"
            },
            {
                "version": "2.7.1",
                "text": "修正新版 Threads 介面下的三無掃描、檢舉 worker、更新通知與管理清單流程，並把三無後續處理收斂成「清除 / 安全名單 / 加入封鎖清單」的本機管理模式。"
            }
        ]
    },
    "supportMessage": "如果留友封有幫上你的忙，也歡迎贊助我來維持功能更新；或到 Chrome Web Store 留一句評價，讓更多人敢安心安裝。謝謝大家的支持。"
};
